### ISSUE TITLE
비쥬얼스튜디오 실행오류

### ISSUE THREAD

**Issue by AnHyojeongg** [909ma/ATM-System-using-by-C-Language#2]
view account.h 파일에서 역참조오류가 나서 실행이 안되네요...

**Comment by 909ma** [comment]
VS에서 실행을 할 때는 바로 실행을 할 수가 없습니다. 아래와 같은 과정을 거치신 후 실행을 하시면 되겠습니다.
1. 새로운 프로젝트 생성
2. 프로젝트 폴더 열기
3. 안에 (1) 헤더 파일과 (2) 소스 코드, (3) 데이터 파일 복사 후 붙여넣기
4. 헤더 파일과 소스 코드를 VS에서 불러오기
이후 소스 코드를 실행했더니 scanf를 쓰지 말고 scanf_s 쓰라는 등의 오류가 난다면 소스 코드 맨 윗줄에
#pragma warning(disable:4996)
추가하시거나 수업 중에 선생님께서 알려주신 방법을 통해 해결하시면 됩니다.

**Comment by AnHyojeongg** [comment]
감사합니다..!
