### ISSUE TITLE
fgets 썼더니 데이터가 이상하게 저장되요 ㅜㅜ

### ISSUE THREAD

**Issue by 909ma** [909ma/ATM-System-using-by-C-Language#4]
원래는 김신혁,10,1234 처럼 저장되야 하는데
김신혁
,10,1234
로 저장되서 데이터 조회가 이상하게 되요 ㅜ 어떻게 하죠?

**Comment by EunjiCh0i** [comment]
fets를 쓸 때에는 반드시 추가해줘야하는 작업이 있습니다.
다음 예제를 보면서 설명하면 
<예시>
fgets(gift->expiry_date,sizeof(gift->expiry_date),stdin);

    for(int i=0; sizeof(gift->expiry_date); i++) {
        if (gift->expiry_date[i] == '\n') {
            gift->expiry_date[i] = '\0';
            break;
        }
    }
fgets를 썼다면 위 예제처럼 fgets 다음행에 
for문과 if문을 사용해 3줄을 추가해서 입력하고,
break ; 까지 입력을 해주어야 
저장값과 데이터조회가 정상정으로 나오는 것을 볼 수 있습니다.

**Comment by 909ma** [comment]
감사합니다!
